/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class OverheadTester */

#ifndef _Included_OverheadTester
#define _Included_OverheadTester
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     OverheadTester
 * Method:    jniOverheadStart
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_OverheadTester_jniOverheadStart
  (JNIEnv *, jclass);

/*
 * Class:     OverheadTester
 * Method:    jniOverheadEnd
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_OverheadTester_jniOverheadEnd
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
